export const tokens_buy = [
  {
    reward: "Stay up and watch KBC episode with Mom",
    type: "experience",
    tokenCost: "30",
    pic: "../images/tokenStorePics/kids-baking-championship.jpg",
    reserved: "",
    reserved_by: "",
  },
  {
    reward: "Temporary tattoo",
    type: "experiene",
    tokenCost: "30",
    pic: "../images/tokenStorePics/temp-tats.png",
    reserved: "",
    reserved_by: "",
  },
  {
    reward: "Small bat plushie",
    type: "item",
    tokenCost: "30",
    pic: "../images/item-pics/bat-sm.jpg",
    reserved: "",
    reserved_by: "",
  },
  {
    reward: "Medium bear plushie",
    type: "item",
    tokenCost: "30",
    pic: "../images/item-pics/bear-med.jpg",
    reserved: "",
    reserved_by: "",
  },
  {
    reward: "Tiny bear plushie",
    type: "item",
    tokenCost: "30",
    pic: "../images/item-pics/bear-tiny.jpg",
    reserved: "",
    reserved_by: "",
  },
  {
    reward: "Small bug plushie",
    type: "item",
    tokenCost: "30",
    pic: "../images/item-pics/bug-sm.jpg",
    reserved: "",
    reserved_by: "",
  },
  {
    reward: "Large cat plushie",
    type: "item",
    tokenCost: "30",
    pic: "../images/item-pics/cat-lg.jpg",
    reserved: "",
    reserved_by: "",
  },
  {
    reward: "Small cat Squashums plushie",
    type: "item",
    tokenCost: "30",
    pic: "../images/item-pics/cat-puff-sm.jpg",
    reserved: "",
    reserved_by: "",
  },
];
